
# the path for saving train\test\validation datasets
dataPath: "./datasets/data_pTCR/"

# device
device: "cuda:1"
numWorker: 32

# the max length of each seq. 
seqMaxLength: 34

# the path for saving ESMc embedding dict
esmcEmbeddingDictPath: "./models/ESMc/ESMcEmbedding/embeddingDict.pkl"
# the path for saving ESMc embeddings
esmcEmbeddingPath: "./models/ESMc/ESMcEmbedding/"
# the path for saving logs
logPath: "./outputs/"
# the path for saving model states
# modelStatePath: "/linyi/workspace/TCRpHLA/ImmuCAGMoE/results/5_fold_evaluation/pTCR/model_states/"

dim_esm: 960

# settings for training and loss function
epochs: 30
learningRate: 1e-4

# batch size for dataloader in the train and test stages
batchSize: 4096